# Generated by Django 4.2.5 on 2023-09-29 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNDEFINED', max_length=255)),
                ('origin', models.CharField(default='UNDEFINED', max_length=255)),
                ('usage', models.CharField(default='UNDEFINED', max_length=255)),
                ('size', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('unit_value', models.FloatField(default=1)),
                ('unit_price', models.FloatField(default=1)),
                ('turnover_time', models.FloatField(default=360)),
                ('demand', models.FloatField(default=0)),
                ('supply', models.FloatField(default=0)),
                ('allocation_ratio', models.FloatField(default=1)),
                ('display_order', models.IntegerField(default=1, null=True)),
                ('image_name', models.CharField(default='UNDEFINED', max_length=255)),
                ('tooltip', models.CharField(default='UNDEFINED', max_length=255)),
                ('monetarily_effective_demand', models.FloatField(default=0)),
                ('investment_proportion', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['simulation', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNDEFINED', max_length=255)),
                ('simulation_number', models.IntegerField(default=1)),
                ('commodity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='economy.commodity')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_stamp', models.IntegerField(default=0)),
                ('state', models.CharField(default='TEMPLATE', max_length=20)),
                ('periods_per_year', models.SmallIntegerField(default=1)),
                ('population_growth_rate', models.FloatField(default=1)),
                ('investment_ratio', models.FloatField(default=1)),
                ('labour_supply_response', models.CharField(default='UNDEFINED', max_length=50)),
                ('price_response_type', models.CharField(default='UNDEFINED', max_length=50)),
                ('melt_response_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=2)),
                ('quantity_symbol', models.CharField(default='#', max_length=2)),
                ('melt', models.FloatField(default=1)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.owner')),
                ('output_scale', models.IntegerField(default=1, null=True)),
                ('output_growth_rate', models.IntegerField(default=1, null=True)),
                ('initial_capital', models.FloatField(default=0, null=True)),
                ('work_in_progress', models.FloatField(default=0, null=True)),
                ('current_capital', models.FloatField(default=0, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('profit_rate', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['simulation', 'pk'],
            },
            bases=('economy.owner',),
        ),
        migrations.CreateModel(
            name='SocialClass',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='economy.owner')),
                ('population', models.IntegerField(default=1000, null=True)),
                ('participation_ratio', models.FloatField(default=1, null=True)),
                ('consumption_ratio', models.FloatField(default=1, null=True)),
                ('revenue', models.FloatField(default=0, null=True)),
                ('assets', models.FloatField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Classes',
                'ordering': ['simulation', 'pk'],
            },
            bases=('economy.owner',),
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=250)),
                ('simulation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(default='UNDEFINED', max_length=255, null=True)),
                ('size', models.FloatField(default=0, null=True)),
                ('requirement', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('demand', models.FloatField(default=0)),
                ('monetary_demand', models.FloatField(default=0)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_stock', to='economy.commodity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='economy.owner')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.simulation')),
            ],
            options={
                'ordering': ['simulation', 'usage_type', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerMoneyStock', to='economy.stock')),
                ('salesStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerStock', to='economy.stock')),
                ('simulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SellerSimulation', to='economy.simulation')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='economy.simulation'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='simulation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='economy.simulation'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuyerMoneyStock', to='economy.stock')),
                ('purchaseStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuyerStock', to='economy.stock')),
                ('simulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BuyerSimulation', to='economy.simulation')),
            ],
        ),
    ]
