# Generated by Django 4.2.5 on 2023-09-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='socialclass',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Social Classes'},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='simulation',
        ),
    ]
