# Generated by Django 4.2.5 on 2023-09-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_alter_industry_options_alter_socialclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='economy.simulation'),
        ),
        migrations.AddField(
            model_name='socialclass',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialclasses', to='economy.simulation'),
        ),
    ]
