# Generated by Django 4.2.5 on 2023-09-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_industry_simulation_socialclass_simulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='simulation_number',
        ),
    ]
