# Generated by Django 4.2.5 on 2023-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_remove_owner_simulation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='UNDEFINED', max_length=200),
        ),
    ]
