# Generated by Django 4.2.5 on 2023-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialclass',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trace',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
    ]
